---
service: aws-configuration-fetcher

frameworkVersion: "^2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  stage: ${opt:stage, env:SERVERLESS_STAGE, 'staging'}
  logRetentionInDays: 30
  environment: ${file(./serverless/environment.yml)}

package:
  individually: true
  exclude: ${file(./serverless/exclude.yml)}

functions: ${file(./serverless/functions.yml)}

