---
service: makenew-serverless-nodejs

frameworkVersion: "^1.58.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  stage: ${opt:stage, env:SERVERLESS_STAGE, 'stg'}
  logRetentionInDays: 30
  environment:
    NODE_ENV: production

package:
  individually: true
  exclude:
    - .drone/**
    - .editorconfig
    - .npmrc
    - .nvmrc
    - .nyc_output/**
    - .yarn-cache/**
    - CHANGELOG.md
    - README.md
    - aws_credentials
    - aws_role_session_name
    - coverage/**
    - examples/**
    - makenew.sh
    - node_modules/.bin/**
    - serverless.yml
    - yarn.lock

functions:
  todo:
    handler: handlers/index.todo
    events:
      - http:
          method: get
          path: /todo
